apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: davidbreau
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # 1Gi / 5Gi / 10Gi
  storageClassName: standard # standard / managed-premium